version: 2
jobs:
  build:
    inline_example/my_inline_job:
      name: mybuild
    docker:
      - image: wecs/circle-ci-gcloud-node:0.1.0
    working_directory: ~/workspace
    environment:
      DEPLOYMENT_NAME: pipeline-cd
      PROJECT_ID: cloud-student-246202
      CLUSTER_NAME: production
      CLUSTER_NAME_STAG: production-stag
      CLOUDSDK_COMPUTE_ZONE: us-central1-a
      CONTAINER_NAME: pipeline-cd
      IMAGE: pipeline-cd
      REG_ID: pipeline-cd
      REG_ID_PROD: pipeline-cd-prod
      IMG_TAG: 0.1.0
      PROJECT_NAME: pipeline-cd
      DEPLOYMENT_ENVIRONMENT: staging
    steps:
      - checkout
      - setup_remote_docker
      - mybuild
      - run:
          name: Build and Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./deployment.sh
            fi
